name: Deploy to various Environments

on:
  push:
    branches:
      - main

jobs:
  deploy_dev:
    uses: ./.github/workflows/re-usable.yml
    with:
      environment: dev

  deploy_staging:
    needs: deploy_dev
    uses: ./.github/workflows/re-usable.yml
    with:
      environment: staging

  deploy_prod:
    needs: deploy_staging
    uses: ./.github/workflows/re-usable.yml
    with:
      environment: production