name: Deployment Workflow

on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string
        default: 'production'

env:
    CONTAINER_REGISTRY: docker.io
    IMAGE_NAME: netflix-clone

jobs: 
  docker_build: 
    runs-on: ubuntu-latest
    steps: 
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Docker Build
      run: docker build -t ${{ env.CONTAINER_REGISTRY }}/${{ vars.DOCKER_USERNAME }}/${{ env.IMAGE_NAME }}:latest .

    - name: Docker Login
      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login --username ${{ vars.DOCKER_USERNAME }} --password-stdin

    - name: Docker Publish 
      run: docker push ${{ env.CONTAINER_REGISTRY }}/${{ vars.DOCKER_USERNAME }}/${{ env.IMAGE_NAME }}:latest

  docker_deploy:
    needs: docker_build
    runs-on: ubuntu-latest
    
    steps:
     - name: Docker Login
       run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login --username ${{ vars.DOCKER_USERNAME }} --password-stdin
    
     - name: Docker Run
       run: |
        docker run -d -p 5173:5173 ${{ env.CONTAINER_REGISTRY }}/${{ vars.DOCKER_USERNAME }}/${{ env.IMAGE_NAME }}:latest
        